version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/docker-volumes/personal/cqrs-postgres:/var/lib/postgresql
      - ~/Desktop/tmp:/tmp
    ports:
      - '10001:5432'

  mongodb:
    image: mongo:5.0
    ports:
      - '10002:27017'
    volumes:
      - ~/docker-volumes/personal/cqrs-mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo